# RTU配置
modbus_port=/dev/ttyS3
modbus_baudrate=4800
modbus_slave_id=1

# TCP配置
modbus_ip=192.168.2.1
modbus_tcp_port=5020

# CAN配置
can_interface=vcan0

# MQTT配置
mqtt_broker=117.78.5.125
mqtt_port=1883
mqtt_client_id=69fe6602cbb0cf6bb958fad5_TempHumi_0_0_2026070207
mqtt_username=69fe6602cbb0cf6bb958fad5_TempHumi
mqtt_password=4897317957bb35698971f91ad52af3a6abedb507fcd044fa1749ff24b43de744
mqtt_topic=$oc/devices/69fe6602cbb0cf6bb958fad5_TempHumi/sys/properties/report

# ★★★ 继电器配置（新增） ★★★
relay_ip=192.168.0.10
relay_port=502
relay_slave_id=1